### ISSUE TITLE
Ansible service task fails with " Could not find the requested service kafka-lag-exporter "

### ISSUE THREAD

**Issue by risg07** [nerdynick/kafka-lag-exporter-ansible#3]
During the playbook execution, at times i'm facing this error though the service file is present at _'/etc/systemd/system/kafka-lag-exporter.service'._

` fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service kafka-lag-exporter: host"}`

Whenever I got this error i had to run the command `systemctl daemon-reload` manually and then execute the playbook, to fix the error. 
So I hope adding `daemon_reload: true` to the systemd module should fix this .

```
- name: Start Kafka Lag Exporter
  systemd:
    daemon_reload: true
    name: "{{ kafka_lag_exporter_service_name }}"
    enabled: true
    state: started
```
